name: fake_store_client
description: A Dart/Flutter package to easily interact with the Fake Store API. Includes models and services to fetch products, users, and cart data.
repository: https://github.com/JamzDeveloper/pragma-dart-package-fake-store-api
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  dartz: ^0.10.1
  http: ^1.4.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
